[tools]
terraform = 'latest'
# https://github.com/anthropics/claude-code/issues/9795
node = '24'
python = 'latest'
ruby = 'latest'
go = 'latest'
rust = 'latest'
lua = 'latest'
actionlint = "latest"
awscli = "latest"
gh = "latest"
lazydocker = "latest"
peco = "latest"
shellcheck = "latest"
claude-code = "latest"
vim = "latest"
bun = "latest"
uv = "latest"
neovim = "latest"
"npm:@commitlint/cli" = "latest"
"npm:@commitlint/config-conventional" = "latest"
"npm:secretlint" = "latest"
"npm:@secretlint/secretlint-rule-preset-recommend" = "latest"
"pipx:ansible" = "latest"
"github:koh-sh/ccnewline" = "latest"
"github:koh-sh/codebuild-multirunner" = "latest"
"github:koh-sh/apcdeploy" = "latest"
fnox = "latest"
"github:jorgerojas26/lazysql" = "latest"

[env]
MISE_PYTHON_DEFAULT_PACKAGES_FILE = '~/.config/mise/default-python-packages'

[settings]
idiomatic_version_file_enable_tools = [
  "go",
  "node",
  "python",
  "ruby",
  "terraform",
]
experimental = true
install_before = "7d"

[settings.python]
compile = false

[tasks.bump]
description = "Bump tools and packages"
run = """
brew update && brew upgrade
brew upgrade --cask wezterm@nightly --no-quarantine --greedy-latest
mise up
"""
